version: "2.1"
services:
  pgbkp:
    build:
      context: .
    image: postgres-bkp
    links:
      - db
    volumes:
      - ./data:${BACKUP_DIR:-/data}
    environment:
      - BACKUP_DIR=${BACKUP_DIR:-/data}
      - PGHOST=${PGHOST:-db}
      - PGDATABASE=${PGDATABASE:-postgres}
      - PGUSER=${PGUSER:-postgres}
      - PGPORT=${PGPORT:-5432}
  db:
    image: postgres:9.6-alpine
